application: time-lyb
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
  - deferred: on
  - remote_api: on


handlers:

- url: /pages
  static_dir: static_pages
  login: required

- url: /reportWorker(.*)
  script: reports.app
  login: admin
- url: /reportPlanner(.*)
  script: planner.app
  login: admin

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /stylesheets
  static_dir: templates/stylesheets
- url: /service/(.*)\.(.*)
  script: services.app
  login: required
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
