application: timelyb-helloword-server
version: 3
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /stylesheets
  static_dir: templates/stylesheets
- url: /service/(.*)\.(.*)
  script: services.app
- url: /pages
  static_dir: static_pages
  login: required

- url: .*
  script: main.app
  login: required

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
